title: "A. Magno Photography"
description: "Photography Portfolio"
baseurl: "/photos"
url: "https://a.magno.me"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  galleries:
    output: false

# Exclude from processing
exclude:
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - .DS_Store

# Image settings
image_formats: ['.jpg', '.jpeg', '.png', '.gif', '.webp'] 